#!/usr/bin/env bash

parallel --ungroup ::: \
  'llama-server --models-preset ~/.llama/models.ini --ui-mcp-proxy' \
  'mcp-proxy --named-server-config ~/.llama/mcp.json --allow-origin "*" --port 8001 --stateless'
