version = 1

[*]
ui-mcp-proxy = true
load-on-startup = false
jinja = true
parallel = 1
tools = all
flash-attn = true
no-mmproj-offload = true
ctx-size = 80000
ctk = q8_0
ctv = q8_0
; GPU
; Vulkan2 = cmp50hx, Vulkan1 = rtx 4070
n-gpu-layers = 999
split-mode = layer

[Gemma4-Uncensored:26B-A4B]
alias = default
device = Vulkan2
model = /data/ssd/models/HauhauCS/Gemma4-26B-A4B-QAT-Uncensored-HauhauCS-Balanced-MTP/Gemma4-26B-A4B-QAT-Uncensored-HauhauCS-Balanced-Q4_K_M.gguf
mmproj = /data/ssd/models/HauhauCS/Gemma4-26B-A4B-QAT-Uncensored-HauhauCS-Balanced-MTP/mmproj-Gemma4-26B-A4B-QAT-Uncensored-HauhauCS-Balanced-BF16.gguf
; it's very slow with mtp
; spec-type = draft-mtp
; model-draft = /data/ssd/models/gemma4/HauhauCS/mtp-gemma-4-26B-A4B-it.gguf
ctx-size = 262144

; Recommended: temperature 0.6 top_k 64 top_p 0.9 min_p 0.05 repeat_penalty 1.1
temperature = 0.6
top-k = 64
top-p = 0.9
min-p = 0.05
repeat-penalty = 1.1
